### PR TITLE
created new script for converting bilingual captions to monolingual caption

### PR DESCRIPTION
**Pull request by tyisme614**
## This pull request contains a new script written in python for converting bilingual cation to monolingual caption.

# Introduction
This script is used for removing english caption from bilingual caption files to make it monolingual.

The english caption line is conventionally placed at the last line of each caption block in srt files. So the newly created script is aimed at removing the last line of each caption block of committed bilingual caption. 

# Env
This script is developed and tested in *python v3.11*.
# Usage
> python3 convert_bilingual_monolingual.py -i \<input_file\> -o \<output_file\>

**Example**
* For instance, the input file name is "test.cn.en.srt", and you name your output file as "output_test.cn.srt" *
> python3 convert_bilingual_monolingual.py -i test.cn.en.srt -o output_test.cn.srt

### CODE REVIEW

**Comment by xianbaoqian** [comment]
Hi @tyisme614  Thanks so much for contributing the script. It looks good to me but I'll let Lewis to double check. 

Also thanks for flagging the issue on Github CI, python 3.6 is no longer supported. I raised https://github.com/huggingface/course/pull/402 to fix that. Do you mind removing the file from the PR. Let's OK to fail the quality check in this PR as it's not related to your script.

**Comment by tyisme614** [comment]
> Hi @tyisme614 Thanks so much for contributing the script. It looks good to me but I'll let Lewis to double check.
> 
> Also thanks for flagging the issue on Github CI, python 3.6 is no longer supported. I raised #402 to fix that. Do you mind removing the file from the PR. Let's OK to fail the quality check in this PR as it's not related to your script.

sure.

**Comment by tyisme614** [comment]
@xianbaoqian I reverted my modification on quality.yml.  
so this PR is clean now.

**Review by lewtun — COMMENTED** [review]
Thank you very much for providing this conversion script @tyisme614 🔥 !!

Would you mind adding your instructions for running it to the README here? https://github.com/huggingface/course/tree/main/subtitles

**Comment by tyisme614** [comment]
> Thank you very much for providing this conversion script @tyisme614 🔥 !!
> 
> Would you mind adding your instructions for running it to the README here? https://github.com/huggingface/course/tree/main/subtitles
> 
> Also we just merged a PR to fix the quality issues with the CI - would you mind rebasing / merging the main branch on yours and pushing again?

no prob~

**Pull request merged**
