### PR TITLE
[ru] Added the glossary and translation guide

### PR DESCRIPTION
**Pull request by 501Good**
The first version of the glossary and the translation guide for Russian. It has been mostly adapted from the German one since most of the guidelines apply to Russian as well.

Any discussion about the choice of terms in the glossary is very welcome here. Once everyone is happy, we can merge it into the main branch.

Issue #75 

@pdumin @blademoon

### CODE REVIEW

**Comment by 501Good** [comment]
To start a discussion, here are some points that I was not sure about:
- Usually, **NLP** is translated as **ОЕЯ** in technical literature. However, in practice, almost everyone in the Russian-speaking NLP community just uses **NLP**. Should we keep the English term or use the official Russian one?
- For **folder** should we use more colloquial term **папка** or more technical one **директория**?

**Comment by pdumin** [comment]
@501Good I think we should use NLP term as more popular. 
I have no preference about директория or папка, I think you can choose any of them and add it to glossary. 


As far as I can see, I already have some discrepancies with the glossary in the translation. Your options seem to be more preferable, so feel free to correct inconsistencies in my translation.

**Comment by 501Good** [comment]
@pdumin Thank you for the suggestions!

I still haven't gone through all the existing chapters, so I will see how the glossary actually fits with the text and make any modifications if needed.

**Comment by 501Good** [comment]
@pdumin @blademoon 
I feel that translating **"prompt"** as **"запрос"** is not very precise since "запрос" is closer to "inquiry", i.e. something that you want to get information about while "prompt" means something that is a beginning of something more. However, I am against keeping it as "prompt" or "промпт".

The only other word that comes to mind is **"затравка"**. The problem with it, however, is that it sounds too colloquial, but at the same time, it feels the closest to the original meaning.

What do you think about it, and do you have any suggestions about it?

**Comment by blademoon** [comment]
@501Good 
This translation was made before the glossary was published. I think: 
1. it is better to specify a specific place (file and timestamp) where there is a constructively controversial point.
2. Translating subtitles is quite a challenge for the following reasons:
- you need to be as close as possible to the terms used by the speaker,
- choose a translation as close as possible to the terminology used in the Russian community,
- not to produce unnecessary neologisms.

I will be revising the translation of the subtitles because it: 
1. was made without taking into account the glossary
2. Doesn't quite match the timestamps.
3. is based on the current English subtitles from YouTube. Not the ones posted in this repository.

**Comment by pdumin** [comment]
@501Good There are many discussions about "prompt" term in other languages. Perhaps we should use "начало текста" or "начальный текст".

**Review by lewtun — APPROVED** [review]
Thanks a lot for adding the translation guide and glossary @501Good and welcome to the Hugging Face community! I'll merge this as-is and people can iterate on it as needed :)

**Pull request merged**
