### PR TITLE
Add "Ask a question" banner

### PR DESCRIPTION
**Pull request by mishig25**
Closes https://github.com/huggingface/course/issues/248

[For the demo, please check the doc link from the bot](https://github.com/huggingface/course/pull/301#issuecomment-1224928619)

Screenshot 2022-08-24 at 10 31 49

Screenshot 2022-08-24 at 10 31 42

For reference, script used to update all mdx files:

```py
from pathlib import Path
import re
re_heading1 = re.compile(r"^(# .*)$", re.MULTILINE)
re_chapter = re.compile(r"chapter([0-9]+)")

p = Path("/Users/mishig/Desktop/course/chapters")
files = [x for x in p.glob("**/*") if x.is_file() and (str(x).endswith(".md") or str(x).endswith(".mdx"))]

for file in files:
    if not re_chapter.findall(str(file)):
        continue
    chapter = int(re_chapter.findall(str(file))[0])
    with open(file, "r", encoding="utf-8-sig") as reader:
        content = reader.read()
    if chapter == 0 or "DocNotebookDropdown" in content:
        continue
    svelte = f"""<CourseFloatingBanner
    chapter={{{chapter}}}
    classNames="absolute z-10 right-0 top-0"
/>"""
    content = re_heading1.sub(rf"\1\n\n{svelte}", content, 1)
    with open(file, "w", encoding="utf-8") as writer:
        writer.write(content)
```

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Awesome work @mishig25 and great idea to roll this out to all the translations too ❤️ 

I've checked the links for the English (and parts of the Spanish) content and this LGTM!

**Comment by mishig25** [comment]
btw, there is no forum link for Chapter 9

could you create one @abidlabs @lewtun ? it should be https://discuss.huggingface.co/t/chapter-9-questions

**Comment by lewtun** [comment]
> btw, there is no forum link for Chapter 9
> 
> could you create one @abidlabs @lewtun ? it should be https://discuss.huggingface.co/t/chapter-9-questions

Ah, I did that when I reviewed the PR - sorry I didn't mention that!

**Comment by mishig25** [comment]
Merging it for now 😊
If we encounter any problems, I'll revert it back

**Comment by mishig25** [comment]
@lewtun now that this PR is merged. Please feel free to make a release based on your convenience 👍

**Comment by lewtun** [comment]
> @lewtun now that this PR is merged. Please feel free to make a release based on your convenience 👍

Will do it today!

**Pull request merged**
