### PR TITLE
[de] Translation Chapter 0

### PR DESCRIPTION
**Pull request by MarcusFra**
Hi, the translation for chapter 0 is finished and ready for being merged. #43

### CODE REVIEW

**Review by lewtun — COMMENTED** [review]
Thanks for kickstarting the German translation @MarcusFra 🇩🇪 !

Could you please add `de` to the `languages` field in the `build_pr_documentation.yml` and `build_documentation.yml` files, e.g.

```
languages: ar bn de en es fa fr he hi ja ko pt ru th tr zh
```

Apart from that, this looks great!

**Comment by MarcusFra** [comment]
Thanks! Done!

**Review by lewtun — APPROVED** [review]
Thanks you! I'll merge once the CI passes - we won't see the website build until `chapter1/1.mdx` is translated, but looking forward to it when it's ready 🔥

**Comment by MarcusFra** [comment]
Just one last comment. I did not translate the alt attribute of the images as I thought these images might also be translated in the future. Or should I translate those attributes yet?

**Comment by lewtun** [comment]
> Just one last comment. I did not translate the alt attribute of the images as I thought these images might also be translated in the future. Or should I translate those attributes yet?

No I think for now it is OK to keep these in English as we currently don't have a simple mechanism to enable external contributors to add translations of the images

**Pull request merged**
