### PR TITLE
Japanese chapter 4

### PR DESCRIPTION
**Pull request by HiromuHota**
This is part of #114.

* [x] chapter4/1.mdx
* [x] chapter4/2.mdx
* [x] chapter4/3.mdx
* [x] chapter4/4.mdx
* [x] chapter4/5.mdx
* [x] chapter4/6.mdx
* [x] _toctree.yml

### CODE REVIEW

**Review by lewtun — COMMENTED** [review]
Hi @HiromuHota, wow this is a real tour de force of a translation - thank you so much!

Depending on your preference:

* we can merge what you have now, minus `chapter4/3.mdx`
* wait until you've had time to translate that final section

Both are perfectly fine with me!

Gently pinging @younesbelkada in case he'd like to give a light review :)

**Comment by younesbelkada** [comment]
Hi @HiromuHota thank you very much for your great work
Looks very good to me :-) ! Would be nice if we can merge it at the same time as https://github.com/huggingface/course/pull/241 to make an annoncement on Twitter, let's see if it will be ready by then

**Comment by HiromuHota** [comment]
@lewtun @younesbelkada Thanks for your comments!
I'll try to finish the `chapter4/3.mdx` this weekend and make it ready for review all together, but if I couldn't make it I would merge what I got so far.

@younesbelkada I'd leave it to you how/when it would be tweeted but thanks for your suggestion!

**Comment by HiromuHota** [comment]
@lewtun @younesbelkada I'm finished with all files in chap4, I'd appreciate your review!

**Comment by younesbelkada** [comment]
I just reviewed the file 3.mdx and looks great for me ! Again thank you very much for your great job 👏

**Comment by HiromuHota** [comment]
@lewtun Thank you for your review. I resolved the conflict, please merge it at your convenience.

**Comment by lewtun** [comment]
Thanks for iterating @HiromuHota - I'll merge deploy this today :)

**Pull request merged**
