### PR TITLE
Translation for 1/4, 1/5 and 1/6.

### PR DESCRIPTION
**Pull request by CaterinaBi**
#45

### CODE REVIEW

**Comment by CaterinaBi** [comment]
Hi @lewtun, when I created the PR, I had a conflict which I didn't create: contents for CH 4 were in the ToC. I'm not translating that chapter so I have no idea how those landed there. I solved the conflict by deleting them, I hope that was the right thing to do. Thanks!

**Comment by CaterinaBi** [comment]
@lewtun the checks are not successful (see above) because the ToC is missing that chapter. I don't even know why it was there in the first place?!

**Comment by CaterinaBi** [comment]
I might have solved the problem alone :) Big girl!

**Review by lewtun — APPROVED** [review]
Hi @CaterinaBi great to see you here again 🤗 !

Thank you for this great set of translations - I hope the experience is also a fun way to learn NLP and Transformers :)

**Comment by CaterinaBi** [comment]
@lewtun it is, indeed! I'm loving it! Have a lovely day 😄

**Pull request merged**
