### PR TITLE
Chapter 0 Persian Translation First Draft

### PR DESCRIPTION
**Pull request by jowharshamshiri**
Added chapter 0 and updated _toctree.yml

Related to #50

### CODE REVIEW

**Comment by jowharshamshiri** [comment]
@lewtun I am having trouble viewing the preview live version at https://moon-ci-docs.huggingface.co/course/course/pr_95, which is the address that gets mailed to me. It auto redirects back to https://moon-ci-docs.huggingface.co/course/pr_34/en/chapter1/1 and when I manually change the URL to something like https://moon-ci-docs.huggingface.co/course/pr_95/fa/chapter2/1, the request just stalls. If this is the same bug you told me about in the last PR, please ignore. I want this mainly to see how it renders with full style, since my local builds throw a sed warning and seem to lack the necessary stylesheets. I will try to see if I can fix that locally later.

**Comment by lewtun** [comment]
Hi @jowharshamshiri yes this is a current limitation in the way we render the website - basically the `fa/chapter1/1.mdx` file needs to exist. 

My suggestion would be to see if @schoobani is still working on that section - if not, you could add it as part of this PR and then we can really see the build :)

**Comment by schoobani** [comment]
> 

yep. I am on it. I will let you know very soon. @jowharshamshiri

**Comment by jowharshamshiri** [comment]
Hi @schoobani, please review.

**Review by schoobani — APPROVED** [review]

**Comment by jowharshamshiri** [comment]
Hi @lewtun, please merge.

**Comment by lewtun** [comment]
Thanks for adding this and apologies for the delay - merging now!

**Comment by schoobani** [comment]
@jowharshamshiri [Sorry to comment on a closed PR!]
You are using **<h>** tags for the subheaders of the text, but instead you should use **#**. 
this causes the right menu not to appear correctly. please fix it in the next PR. thanks.

**Comment by jowharshamshiri** [comment]
> @jowharshamshiri [Sorry to comment on a closed PR!] You are using tags for the subheaders of the text, but instead you should use **#**. this causes the right menu not to appear correctly. please fix it in the next PR. thanks.

Hey just saw this, I am doing it bc in the current version of the Hugging Face docs, we need this for the page to render correctly in the preview. It will be LTR if we don't do it.

**Pull request merged**
