### PR TITLE
[FR] Add FAQ and more

### PR DESCRIPTION
**Pull request by lbourdois**
Hi @lewtun 

This PR adds to the French version :
- the FAQ
- the glossary
- Matt's modifications on TF code

We must be pretty good for the French version now :)

### CODE REVIEW

**Comment by lbourdois** [comment]
Hummm I get an error "Process completed with exit code 2." but I don't know how to correct it.

**Comment by lewtun** [comment]
Hey @lbourdois we're currently migrating our hub docs to a more stable system - can you try rebasing / merging on `main` and pushing again?

**Comment by lewtun** [comment]
Hmm it seems something is not working - I'll take a look

**Review by lewtun — APPROVED** [review]
Great, I fixed the build by merging `main` again - thanks for the final improvements to the French version 🔥 !

**Pull request merged**
