### PR TITLE
Chinese - Chapter 3finished

### PR DESCRIPTION
**Pull request by 1375626371**
Hello, we have finished the translation of chapter 3, please check. Among them, sections 3,6 of the chapter 2 were completed by @petrichor1122 , sections 1, 4, 5 of the chapter 2 were completed by @zhlhyx , section 2 and 3_tf of the chapter 2  were completed by me.

### CODE REVIEW

**Comment by lewtun** [comment]
Hey @1375626371 thanks for the latest batch of translations! It seems the code formatter needs to be run with:

```
make style
```

Would you mind doing that and pushing again?

**Comment by 1375626371** [comment]
> Hey @1375626371 thanks for the latest batch of translations! It seems the code formatter needs to be run with:
> 
> ```
> make style
> ```
> 
> Would you mind doing that and pushing again?

Of course, but I still can't pass the quality check after run `make style`. What should I do?

**Comment by lewtun** [comment]
> Of course, but I still can't pass the quality check after run `make style`. What should I do?

I've pushed a fix by:

* Running `make style`
* Committing the formatted files

It's a bit strange that various files unrelated to your PR are changed - my best guess is that the Git commit history on your fork is somehow out of sync with the main repo. To test that could you try running the following:

```
git fetch upstream
git checkout main
git rebase upstream/main
```

I'll check the format changes, but if it all looks good I'll go ahead and merge this - thanks for the translation!!

**Comment by 1375626371** [comment]
> > Of course, but I still can't pass the quality check after run `make style`. What should I do?
> 
> I've pushed a fix by:
> 
> * Running `make style`
> * Committing the formatted files
> 
> It's a bit strange that various files unrelated to your PR are changed - my best guess is that the Git commit history on your fork is somehow out of sync with the main repo. To test that could you try running the following:
> 
> ```
> git fetch upstream
> git checkout main
> git rebase upstream/main
> ```
> 
> I'll check the format changes, but if it all looks good I'll go ahead and merge this - thanks for the translation!!

Ok Thank you for suggestion.   I'll try to do that before the next commit

**Pull request merged**
