### PR TITLE
zh-CN - Chapter 6finished

### PR DESCRIPTION
**Pull request by 1375626371**
we have completed the translation of chapters 6, below is the list of contributors
## @petrichor1122 
Fast tokenizers in the QA pipeline.md 391  
Fast tokenizers' special powers.md 323  
Normalization and pre-tokenization.md 85 
## @1375626371 
Introduction.md 42 
10.mdx 269  
Training a new tokenizer from an old one.md 193  
Building a tokenizer, block by block.md 447  
Tokenizers, check!.md 13  
## @zhlhyx 
Byte-Pair Encoding tokenization.md 285  
Unigram tokenization.md 309  
WordPiece tokenization.md 302

### CODE REVIEW

**Comment by 1375626371** [comment]
Before I submit the changes, I will synchronize the data of `huggingface:main branch`, and then when I submit it, I find that there are changes in addition to the chapter I submitted, I am very confused. I'm currently ignoring changes other than the chapter I commit and then committing. I found that the changes are in the code formatting section. I also tried running `git checkout main -- chapters/fr` but found no changes.
I can't solve this problem at the moment, I need to trouble you to help me solve it.
Thank you!

**Comment by lvwerra** [comment]
The style check should be fixed now. You can do it usually with 

```bash
make style && make quality
```

You reverted the merge of main into your branch which deleted a bunch of files in this commit:https://github.com/huggingface/course/pull/290/commits/6403eaa453188e79b08473868ff40dd4060669f7

We need to revert that commit before merging your contribution. I can do it for you if you like, just let me know.

**Comment by 1375626371** [comment]
> The style check should be fixed now. You can do it usually with
> 
> ```shell
> make style && make quality
> ```
> 
> You reverted the merge of main into your branch which deleted a bunch of files in this commit:[6403eaa](https://github.com/huggingface/course/commit/6403eaa453188e79b08473868ff40dd4060669f7)
> 
> We need to revert that commit before merging your contribution. I can do it for you if you like, just let me know.



> The style check should be fixed now. You can do it usually with
> 
> ```shell
> make style && make quality
> ```
> 
> You reverted the merge of main into your branch which deleted a bunch of files in this commit:[6403eaa](https://github.com/huggingface/course/commit/6403eaa453188e79b08473868ff40dd4060669f7)
> 
> We need to revert that commit before merging your contribution. I can do it for you if you like, just let me know.

Of course, since I am not very proficient in the operation of github branches, there may be some oversights. Thanks a lot if you can help fix it.

**Review by lvwerra — APPROVED** [review]
Thanks for working on this. Looks good now!

**Pull request merged**
