### PR TITLE
Translation Chapter 4

### PR DESCRIPTION
**Pull request by fabridamicelli**
So I am finally done with this one.
I'd great if a native speaker like @MarcusFra or @JesperDramsch could take a look at it, just to stay on the safe side and catch silly mistakes I might have done :)

### CODE REVIEW

**Comment by lewtun** [comment]
Hey @fabridamicelli thanks so much for contributing this translation! Would you mind resolving the merge conflict so that we can build the course website in this PR for review?

**Comment by lewtun** [comment]
Thanks for resolving the conflicts! I just realised that the German chapters are still missing `chapter1/1.mdx` so we won't be able to render this on hf.co/course until then 

I had a quick read of your translation and it looks pretty good to me!

**Comment by fabridamicelli** [comment]
@lewtun I just fixed a couple of passages that I forgot to delete during the translation.

The documentation actually gets rendered despite missing the first chapter. You can see it by *first* selecting the chapter (in this case 4) in the English version and once on it change the language to DE. [Here](https://moon-ci-docs.huggingface.co/course/pr_325/de/chapter4/1?fw=pt) is the current docu version

**Comment by lewtun** [comment]
> @lewtun I just fixed a couple of passages that I forgot to delete during the translation.
> 
> The documentation actually gets rendered despite missing the first chapter. You can see it by _first_ selecting the chapter (in this case 4) in the English version and once on it change the language to DE. [Here](https://moon-ci-docs.huggingface.co/course/pr_325/de/chapter4/1?fw=pt) is the current docu version

Hah, that's a cool hack I didn't know about :)

Let's see what @MarcusFra @JesperDramsch think about the translation - otherwise, I'm happy to merge it!

**Comment by fabridamicelli** [comment]
> > @lewtun I just fixed a couple of passages that I forgot to delete during the translation.
> > The documentation actually gets rendered despite missing the first chapter. You can see it by _first_ selecting the chapter (in this case 4) in the English version and once on it change the language to DE. [Here](https://moon-ci-docs.huggingface.co/course/pr_325/de/chapter4/1?fw=pt) is the current docu version
> 
> Hah, that's a cool hack I didn't know about :)
> 
> Let's see what @MarcusFra @JesperDramsch think about the translation - otherwise, I'm happy to merge it!

Sounds good to me :)

**Comment by lewtun** [comment]
I'm going to merge this now - we can always iterate with tweaks on the grammar if needed :)

**Comment by fabridamicelli** [comment]
> I'm going to merge this now - we can always iterate with tweaks on the grammar if needed :)

absolutely fine for me, thank you!

**Comment by JesperDramsch** [comment]
Hey folks, sorry for the delay. I'm a little oversubscribed (and a little under-motivated as we don't have ch1 yet). I bet it looks good, happy to look through the course when we have a more complete translation and I have a bit more time.

**Comment by MarcusFra** [comment]
Hello all,

sorry I'm lagging behind on chapter 1! I got sick at the wrong time and then had to catch up on some deadlines. I'm taking care of finishing chapter 1 this weekend and will also take a look at chapter 3 & 4.

**Comment by fabridamicelli** [comment]
no problem @JesperDramsch and @MarcusFra! I still have the second part of the chapter before me, so you will also have the chance to look at it when I am done with that second bulk.

**Pull request merged**
