### PR TITLE
Add zh-CN machine translations.

### PR DESCRIPTION
**Pull request by chenglu**
The goal of this PR is to add **bilingual** Chinese subtitles based on the accurate English subtitles (#384) with machine translation.

### Why use bilingual subtitles for collaboration?

Since our localized version subtitles are done by machine translation, we may need to reference to the original (English) ones, and the bilingual subtitles might could help, since in this type of subtitle, we are putting the localized words on top and English on the bottom, so it will be easier for reviewers to review. And when we publish the localized ones to YouTube, we could add a new function to `generate_subtitles.py` to remove the English lines.

image

If we are OK with the bilingual subtitles plan, I could use the tools to generate other languages, too.

These zh-CN translations were also:
- Replaced 您 to 你
- Added space between English and Chinese
- Corrected the translation of "Hugging Face"
- Corrected part of Transformers translations

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thank you very much for adding the `zh-CN` machine translations @chenglu 🚀 !

I like your idea of supporting a bilingual format and it would be quite easy to strip out the English parts before adding them to YouTube. Would you like to add that logic to `generate_subtitles.py` or prefer I do it?

**Comment by chenglu** [comment]
Hi Lewis, thanks for your great support! 

For adding the new function to the script, considering this is not kind of urgent work, I'd like to introduce Steven @tyisme614 to give it a try, buuut... if we're not finished this after all the zh-CN subtitles are reviewed, I'll have to ask your help to do it, WDYT? 🥺

**Comment by chenglu** [comment]
My vote goes to merge this PR now, since @xianbao and me are planning to organize the other Chinese language volunteers for the further collaboration, directly open PR to the main repo will be easier for us. 
Thanks again for the great help, Lewis and Tiezhen!

**Comment by lewtun** [comment]
Done and thank you for working on making the course accessible to Chinese speakers!

**Pull request merged**
