### PR TITLE
[TR] Translated Chapter 1.6 🤗

### PR DESCRIPTION
**Pull request by tanersekmen**
I will translate other part of chapters this week.

### CODE REVIEW

**Review by tanersekmen — COMMENTED** [review]
added chapter 1 - 6

**Review by lewtun — COMMENTED** [review]
Thanks for this translation @tanersekmen ! Can you please add this section to the `_toctree.yml` file? 

Then we can test the content will build :)

**Comment by tanersekmen** [comment]
I fixed from there : https://github.com/huggingface/course/pull/185 can you check this pr?

**Comment by lewtun** [comment]
Closing in favour of #185

**Pull request closed without merging**
