### PR TITLE
Part 7: Training a causal... fixes

### PR DESCRIPTION
**Pull request by CakeCrusher**
typos
missing code
code consistency

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thanks for the fixes!

**Comment by lewtun** [comment]
Oh it seems that there's some code formatting needed. Could you please run:

```
pip install -r requirements.txt
make style
```

Thanks!

**Comment by CakeCrusher** [comment]
@lewtun ran styling.

**Comment by lewtun** [comment]
Thanks for the fixes!

**Pull request merged**
