### PR TITLE
Fixes space link in gradio blocks events page

### PR DESCRIPTION
**Pull request by dawoodkhan82**

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
LGTM!

**Comment by MKhalusova** [comment]
The change looks good to me, but I wonder why doc_builder fails. cc @mishig25 any ideas?

**Comment by osanseviero** [comment]
From https://github.com/huggingface/course/actions/workflows/build_pr_documentation.yml it seems i'ts been broken for some weeks :thinking:

**Comment by mishig25** [comment]
Doc-build will work after rebasing from main (specifically, this change https://github.com/huggingface/course/pull/618)

**Review by mishig25 — APPROVED** [review]
lgtm

**Pull request merged**
