### PR TITLE
doc_change(translation): translating course from english to gujarati

### PR DESCRIPTION
**Pull request by ashwathim**
translated: course/gj/chapter0/1.mdx - introduction

### CODE REVIEW

**Comment by ashwathim** [comment]
merging

**Comment by ashwathim** [comment]
Issue raised: https://github.com/huggingface/course/issues/122

**Review by lewtun — COMMENTED** [review]
Thank you for this contribution @ashwathim - this looks great! 

Would you mind adding `gj` to the `languages` field of the `build_pr_documentation.yml` and `build_documentation.yml` files as follows:

```
languages: ar bn en es fa fr gj he hi ja ko pt ru th tr zh
```

**Comment by ashwathim** [comment]
Thank you @lewtun for your review, this is my first open source work, so all feedback is appreciated. I have updated the build files.

**Comment by lewtun** [comment]
> Thank you @lewtun for your review, this is my first open source work, so all feedback is appreciated. I have updated the build files.

Congratulations on your first open-source contribution 🥳 ! Thank you for adding the language code to the CI - when it passes I think this is good to go!

**Comment by ashwathim** [comment]
@lewtun thank you!, i am getting a  build error (below), but not sure why that is happening, could you please advice on what could be the issue? :

```bash
Generating frontmatter:   0%|          | 0/1 [00:00<?, ?it/s]
Generating frontmatter:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/doc-builder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/doc_builder/commands/doc_builder_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/doc_builder/commands/build.py", line 89, in build_command
    build_doc(
  File "/usr/local/lib/python3.8/site-packages/doc_builder/build_doc.py", line 409, in build_doc
    generate_frontmatter(output_dir)
  File "/usr/local/lib/python3.8/site-packages/doc_builder/build_doc.py", line 323, in generate_frontmatter
    content = generate_frontmatter_in_text(content, file_name=file_name)
  File "/usr/local/lib/python3.8/site-packages/doc_builder/build_doc.py", line 304, in generate_frontmatter_in_text
    frontmatter = root.get_frontmatter()
AttributeError: 'NoneType' object has no attribute 'get_frontmatter'
```

**Comment by lewtun** [comment]
I think you figured it out @ashwathim! I was able to build the content locally and will merge once the CI passes 🤗

**Pull request merged**
