### PR TITLE
[PT] add 7 and 7.1

### PR DESCRIPTION
**Pull request by LincolnVS**
#51

### CODE REVIEW

**Review by johnnv1 — APPROVED** [review]

**Review by lewtun — COMMENTED** [review]
Thanks for this contribution @LincolnVS 🚀 !! Would you mind resolving the merge conflicts and pushing again? Then we can merge :)

**Comment by LincolnVS** [comment]
@lewtun solved 🚀🚀🚀

**Comment by LincolnVS** [comment]
> Hey @LincolnVS sorry to be a bother - there's one final set of merge conflicts to be resolved. Would you mind fixing them?

no problem @lewtun, solved 😄

**Comment by lewtun** [comment]
Thanks a lot!

**Pull request merged**
