### PR TITLE
Italian translation - chapter 4

### PR DESCRIPTION
**Pull request by ClonedOne**
Hello, I'm opening a PR for chapter 4 of the Italian translation of the course, as per #45

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Awesome job translating the whole chapter @ClonedOne ❤️ ! It looks great to me :)

**Comment by CaterinaBi** [comment]
Hi @ClonedOne, how are you? Congratulations on completing the translation of chapter 4! I'm almost done translating chapter 1. Have you had your translation proofread? I was thinking that maybe we could proofread each other's work? Let me know 😄

**Comment by ClonedOne** [comment]
Hi @CaterinaBi I haven't really thought about external proofreading. I'd be happy to proofread your work, and you should totally feel free to proofread mine and send PRs with fixes :D.  I am a little busy right now though, so it's going to take me some time before I can get to do that.

**Comment by CaterinaBi** [comment]
Hello @ClonedOne, I will when I'm done translating the first chapter! I'll keep you updated! Caterina

**Pull request merged**
